# Generated by Django 3.1.6 on 2021-08-17 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doafumcadmodel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='BiggerIncome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=70)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Ethnicitis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Gadgets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=35)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='HomeSituation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Incapacitis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='InternetAccess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=75)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='MaritalStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=35)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Religion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Schooling',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=35)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p00_email', models.CharField(blank=True, max_length=80, null=True, verbose_name='Email da Google')),
                ('p01_name', models.CharField(max_length=50, verbose_name='Nome:')),
                ('p03_name_social', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nome:')),
                ('p03_phone', models.CharField(blank=True, max_length=14, null=True, verbose_name='Meios de Entrar em contato')),
                ('p03_is_whatsapp', models.CharField(default='N', max_length=1)),
                ('p04_birth_date', models.CharField(blank=True, max_length=10, null=True)),
                ('p05_CPF', models.CharField(blank=True, max_length=14, null=True)),
                ('p05_RG', models.CharField(blank=True, max_length=14, null=True)),
                ('p05_RG_emissor', models.CharField(blank=True, max_length=20, null=True)),
                ('p05_RG_Estado', models.CharField(blank=True, max_length=2, null=True)),
                ('P08_is_student', models.CharField(blank=True, max_length=3, null=True)),
                ('p13_0_social_information', models.CharField(default='N', max_length=1)),
                ('p14_lives_with', models.IntegerField(blank=True, default=0, null=True)),
                ('p17_responsible_name', models.CharField(max_length=50, verbose_name='Nome:')),
                ('p18_responsible_email', models.CharField(blank=True, max_length=80, null=True)),
                ('p19_responsible_phone', models.CharField(blank=True, max_length=14, null=True)),
                ('p19_same_participante', models.CharField(default='N', max_length=1)),
                ('p30_public_place', models.CharField(blank=True, max_length=75)),
                ('p31_number_place', models.CharField(blank=True, max_length=8)),
                ('p32_district', models.CharField(blank=True, max_length=60)),
                ('p34_cep', models.CharField(blank=True, max_length=9)),
                ('p06_gender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='participante.gender')),
                ('p07_marital_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='participante.maritalstatus')),
                ('p08_schooling', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='participante.schooling')),
                ('p09_ethnicity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='participante.ethnicitis')),
                ('p10_incapacity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='participante.incapacitis')),
                ('p11_gadgets', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='participante.gadgets')),
                ('p12_internet_access', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='participante.internetaccess')),
                ('p13_income_family', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='participante.income')),
                ('p15_home_situation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='participante.homesituation')),
                ('p16_bigger_income', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='participante.biggerincome')),
                ('p33_cidade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='doafumcadmodel.cidade')),
                ('p40_activities', models.ManyToManyField(to='participante.Activities')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
