# Generated by Django 3.2.5 on 2021-07-13 22:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Boleto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reftran', models.CharField(db_column='refTran', max_length=17, unique=True)),
                ('documentopessoa', models.CharField(blank=True, db_column='documentoPessoa', max_length=14, null=True)),
                ('datavencimento', models.DateField(blank=True, db_column='dataVencimento', null=True)),
                ('destino', models.CharField(blank=True, max_length=14, null=True)),
                ('raw', models.TextField(blank=True, null=True)),
                ('codigobarras', models.CharField(blank=True, db_column='codigoBarras', max_length=54, null=True)),
                ('pago', models.IntegerField()),
                ('valor', models.IntegerField()),
                ('datapagamento', models.DateField(blank=True, db_column='dataPagamento', null=True)),
                ('dataemissao', models.DateField(blank=True, db_column='dataEmissao', null=True)),
                ('valordescontado', models.IntegerField(blank=True, db_column='valorDescontado', null=True)),
                ('valorpago', models.IntegerField(blank=True, db_column='valorPago', null=True)),
                ('datacompensacao', models.DateField(blank=True, db_column='dataCompensacao', null=True)),
                ('valorfumcad', models.IntegerField(blank=True, db_column='valorFUMCAD', null=True)),
                ('tempo', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Boleto',
                'verbose_name_plural': 'Boletos',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=40)),
                ('idconv', models.CharField(max_length=10)),
                ('convenio', models.CharField(max_length=10)),
                ('banner', models.CharField(blank=True, max_length=255, null=True)),
                ('porcentagemfundo', models.IntegerField()),
                ('possuiprojetos', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Cidade',
                'verbose_name_plural': 'Cidades',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Instituicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj', models.CharField(max_length=14)),
                ('senha', models.CharField(max_length=64)),
                ('foto', models.CharField(max_length=150)),
                ('logo', models.CharField(blank=True, max_length=512, null=True)),
                ('nome', models.CharField(max_length=75)),
                ('descricao', models.CharField(blank=True, max_length=5000, null=True)),
                ('endereco', models.CharField(blank=True, max_length=50, null=True)),
                ('telefone', models.CharField(blank=True, max_length=11, null=True)),
                ('whatsapp', models.CharField(blank=True, max_length=12, null=True)),
                ('publico', models.CharField(blank=True, max_length=5000, null=True)),
                ('acoes', models.CharField(blank=True, max_length=5000, null=True)),
                ('dimensionamento', models.CharField(blank=True, max_length=5000, null=True)),
                ('pretencoes', models.CharField(blank=True, max_length=5000, null=True)),
                ('porquedoar', models.CharField(blank=True, db_column='porqueDoar', max_length=5000, null=True)),
                ('sigla', models.CharField(max_length=50)),
                ('site', models.CharField(blank=True, max_length=100, null=True)),
                ('facebook', models.CharField(blank=True, max_length=100, null=True)),
                ('permissoes', models.IntegerField()),
                ('ativo', models.IntegerField(blank=True, null=True)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
                ('idcidade', models.IntegerField(db_column='idCidade')),
                ('projetodatainicio', models.DateField(blank=True, db_column='projetoDataInicio', null=True)),
                ('projetodataencerramento', models.DateField(blank=True, db_column='projetoDataEncerramento', null=True)),
                ('projetometaarrecadacao', models.IntegerField(blank=True, db_column='projetoMetaArrecadacao', null=True)),
                ('login', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'verbose_name': 'Instituição',
                'verbose_name_plural': 'Instituições',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Patrocinador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj', models.CharField(max_length=14)),
                ('senha', models.CharField(max_length=64)),
                ('foto', models.CharField(max_length=150)),
                ('logo', models.CharField(blank=True, max_length=512, null=True)),
                ('nome', models.CharField(max_length=75)),
                ('descricao', models.CharField(blank=True, max_length=5000, null=True)),
                ('endereco', models.CharField(blank=True, max_length=50, null=True)),
                ('telefone', models.CharField(blank=True, max_length=11, null=True)),
                ('whatsapp', models.CharField(blank=True, max_length=12, null=True)),
            ],
            options={
                'verbose_name': 'Patrocinador',
                'verbose_name_plural': 'Patrocinadores',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento', models.CharField(max_length=14, unique=True)),
                ('senha', models.CharField(max_length=64)),
                ('tipodocumento', models.IntegerField(db_column='tipoDocumento')),
                ('nome', models.CharField(max_length=50)),
                ('email', models.CharField(blank=True, max_length=40, null=True)),
                ('telefone', models.CharField(blank=True, max_length=15, null=True)),
                ('cep', models.CharField(max_length=8)),
                ('logradouro', models.CharField(max_length=60)),
                ('cidade', models.CharField(max_length=50)),
                ('bairro', models.CharField(max_length=30)),
                ('numero', models.CharField(max_length=5)),
                ('complemento', models.CharField(blank=True, max_length=20, null=True)),
                ('uf', models.CharField(max_length=2)),
            ],
            options={
                'verbose_name': 'Pessoa',
                'verbose_name_plural': 'Pessoas',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Patrocinador_Cidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=150)),
                ('cidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doafumcadmodel.cidade')),
                ('patrocinador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doafumcadmodel.patrocinador')),
            ],
            options={
                'verbose_name': 'Patrocinador_Cidade',
                'verbose_name_plural': 'Patrocinadores_Cidades',
                'ordering': ['id'],
            },
        ),
    ]
