# Generated by Django 3.1.6 on 2021-08-17 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=40)),
                ('idconv', models.CharField(max_length=10)),
                ('convenio', models.CharField(max_length=10)),
                ('banner', models.CharField(blank=True, max_length=255, null=True)),
                ('porcentagemfundo', models.IntegerField()),
                ('possuiprojetos', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Cidade',
                'verbose_name_plural': 'Cidades',
                'ordering': ['id'],
            },
        ),
    ]
