# Generated by Django 3.1.6 on 2021-08-17 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doafumcadmodel', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cidade',
            old_name='nome',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='cidade',
            name='banner',
        ),
        migrations.RemoveField(
            model_name='cidade',
            name='convenio',
        ),
        migrations.RemoveField(
            model_name='cidade',
            name='idconv',
        ),
        migrations.RemoveField(
            model_name='cidade',
            name='porcentagemfundo',
        ),
        migrations.RemoveField(
            model_name='cidade',
            name='possuiprojetos',
        ),
        migrations.AddField(
            model_name='cidade',
            name='country',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='cidade',
            name='state',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
